version: '3'
services:
  backend:
    build: .
    ports:
      - "5001:5000"
    environment:
      - PASSWORD=${PASSWORD}
      - FLASK_APP=/app/__init__.py
    volumes:
      - ./server:/app
    command: python -m flask run --host=0.0.0.0 --port=5000